### ISSUE TITLE
I would like to do a PR to clean up all the code it should be almost all whitespace changes

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#15]
It is automated but will touch every file. Otherwise, any code file or spelling check will cause virtually every line to change and make reviews much more difficult. The binary should be identical before and after.

The one change that is more than whitespace is endregion will get a name matching region name and removal of unused using statements.

If you do compare with ?w1 it will remove all the whitespace difference and have a way to ignore new-line there are few changes.

**Comment by paul1956** [comment]
@kirsan31 I used WinMerge to compare Master with this PR and had it ignore spaces and new lines, then the only difference you see are endregion , removal of unused usings and 4 files where private was missing and was added.
It took about 15 minutes to do every file. A typical file below, some have as just 1 line different.
![image](https://user-images.githubusercontent.com/12789369/200719922-f9242c53-cba6-4322-b1b2-00af921b2257.png)

**Comment by kirsan31** [comment]
Thank you very match for your help @paul1956. I will definitely look at all of this, but a bit later, have very busy days for now...

**Comment by paul1956** [comment]
I leave country next Tuesday for 2 months at sea, so it may be a while unless I can respond after that. The other PR is trivial you might want to look at it first.

**Comment by kirsan31** [comment]
Сlosed as discussed in https://github.com/kirsan31/winforms-datavisualization/pull/14 and https://github.com/kirsan31/winforms-datavisualization/pull/16.
