### ISSUE TITLE
When I clone repo, I get error 

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#20]
NU1301	The local source 'C:\Users\PaulM\Source\Repos\winforms-datavisualization\NuGet\BuildOut' doesn't exist.

I don't see that directory NuGet directory in the clone

![image](https://user-images.githubusercontent.com/12789369/211134559-8677d6e7-9cbf-4566-bfe0-f8bcebdf3402.png)

**Comment by kirsan31** [comment]
Thank you @paul1956 for notice this. I will add them...

it's not really a problem - the errors goes away after the build, but another one appears - `ChartSamples.csproj` cannot be built until you restart the solution.

After adding this folders we will see this errors after solution load:
![image](https://user-images.githubusercontent.com/17767561/211160341-8db40cfa-4bdc-4cdc-9452-4b21bad0c7d2.png)
And all will be ok after first build. 👍
