### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#21]
Is there any way to make line width in Legend wider without make the line plotted wider.
![image](https://user-images.githubusercontent.com/12789369/211140317-55a599d5-58ba-48ac-8aa7-529ba3664c6f.png)

BG line is wider in both chart and legend and looks good but if I make the other lines wider the chart does not look correct.

![image](https://user-images.githubusercontent.com/12789369/211140423-573f4223-c905-4081-b671-b9a795420b73.png)

The 3 colors Min Basal, BG and High Limit all look close in the Legend but in the chart the look different. I would like them to be wider in just the Legend.

**Comment by kirsan31** [comment]
Yes, you can achieve this thru custom legend items:

![image](https://user-images.githubusercontent.com/17767561/211161940-2e1f5c0e-7bba-4649-9e66-d3955c7efdcb.png)

You can increase line width up to 4 pixel, or use rectangle type.
