### ISSUE TITLE
Suggested Enhancement - Make the location of AxisY and AxisY2 available

### ISSUE THREAD

**Issue by Panache1** [kirsan31/winforms-datavisualization#27]
I would like to be able to get the location of AxisY and AxisY2 in a chart. There are a lot of things I would like to do with this information, like aligning a label or title with the axis, checking to see if the mouse is on the chart itself, etc. However, as a simple example, I would just like to be able to draw a horizontal line between the two y axes and not have it extend past them.

Using AxisX.Minimum and Maximum works, as long as all of the values appear on the chart. However, if the chart has a scroll bar, the lines extend to the left of AxisY or the right of AxisY2 depending on where the chart is scrolled.

```cs
public Form1() 
{
    InitializeComponent();

    // Add an event handler
    this.chart1.Paint += new PaintEventHandler(this.DrawLine);

    // Add some values
    for (int value = 0; value <= 10; value++)
        chart1.Series[0].Points.AddXY(value, value);

    // DrawLine no longer works when a scroll bar is added,
    //chart1.ChartAreas[0].AxisX.ScaleView.Zoom(0, 5);
}

// Draw a line from axisY to axisY2
private void DrawLine(object sender, PaintEventArgs e) 
{
    // Get the left and right edges of the values
    // This only works if all of the values appear on the chart at the same time, ie. there is no scroll bar
    // How can I find the locations of axisY and axisY2 as drawn on the chart?
    int axisYLocation = (int)chart1.ChartAreas[0].AxisX.ValueToPixelPosition(chart1.ChartAreas[0].AxisX.Minimum);
    int axisY2Location = (int)chart1.ChartAreas[0].AxisX.ValueToPixelPosition(chart1.ChartAreas[0].AxisX.Maximum);

    e.Graphics.DrawLine(new Pen(Color.Red, 5), new Point(axisYLocation, 50), new Point(axisY2Location, 50)); 
}
```
[Sorry -- I don't know why when I add code it breaks it up this way.]

Therefore, what I need is the location of AxisY and AxisY2 as displayed.  I'm assuming your code already contains this information, so I would think it wouldn't be very hard to expose the values.  I'd be happy to help make this contribution, but I'm a self-taught programmer, so I don't know how much help I would be.

Thank you for the great effort in making this available for .NET 6!

**Comment by kirsan31** [comment]
> [Sorry -- I don't know why when I add code it breaks it up this way.]


To add multiple code blocs you need to type three tilde then language (if needed) . For example:
![image](https://user-images.githubusercontent.com/17767561/215855131-b5fe364c-ed83-4312-b633-f8dbb9b5aad2.png)
will do:
```cs
int axisYLocation = (int)chart1.ChartAreas[0].AxisX.ValueToPixelPosition(chart1.ChartAreas[0].AxisX.Minimum);
int axisY2Location = (int)chart1.ChartAreas[0].AxisX.ValueToPixelPosition(chart1.ChartAreas[0].AxisX.Maximum);
```

As quick thots on your question - try to use: 
```cs
chart1.ChartAreas[0].AxisX.ScaleView.ViewMinimum;
chart1.ChartAreas[0].AxisX.ScaleView.ViewMaximum;
```

instead of 

```cs
chart1.ChartAreas[0].AxisX.Minimum;
chart1.ChartAreas[0].AxisX.Maximum
```

`ScaleView` just used for zooming...

**Comment by Panache1** [comment]
Awesome!  That does exactly what I want.
