### ISSUE TITLE
Question: is there a way to make Annotations Position Better?

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#29]
![image](https://user-images.githubusercontent.com/12789369/219936954-553bf8dd-8a7c-4cc6-9e04-ae2a73a46f80.png)
Overlapping makes some them impossible to read and there is lots of white space below

**Comment by kirsan31** [comment]
I think that `SmartLabelStyle` settings is that what you need. Also you can try to play with `Anchor`, or even to position annotation manually.
![image](https://user-images.githubusercontent.com/17767561/219937342-cb1b3216-4098-4ced-894f-9a785875e87f.png)

**Comment by paul1956** [comment]
It's not the marker it's the line from the marker, I need a way to know Z-Order so I can move the ones where line is bocking to back, which is only 2 now.
![image](https://user-images.githubusercontent.com/12789369/219939388-84cd5f1a-b931-4626-bc39-c958515f1f68.png)

**Comment by kirsan31** [comment]
> I need a way to know Z-Order

If I'm not mistaken, the z order works the same way as with series: the larger the index, the closer to us. Those. the annotation at index 1 will overlap the annotation with index 0.

**Comment by paul1956** [comment]
@kirsan31 There is a very easy solution to this issue. If you want to put it somewhere in case others have the same issue. If you BringToFront the last CalloutAnnotiation, the code automatically recalculates the position of all the Callouts so they don't overlap.

**Comment by kirsan31** [comment]
> There is a very easy solution to this issue. If you want to put it somewhere in case others have the same issue. If you BringToFront the last CalloutAnnotiation, the code automatically recalculates the position of all the Callouts so they don't overlap.

Nice catch, I didn't even know about `Annotation.BringToFront ()` method 😳
