### ISSUE TITLE
How do I get designer to work

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#3]
I want to see at least the chart on a form/Panel

**Comment by kirsan31** [comment]
It must work after you correctly reference `System.Windows.Forms.DataVisualization.dll`. You can test it in `DesignerTest` project (you need to reference by dll not by project first due to designer bug).

https://user-images.githubusercontent.com/17767561/190362082-e830a9ee-181f-45c0-8ad1-8e5cd5387642.mp4

**Comment by kirsan31** [comment]
Or if your question was about absent of `chart` control in control toolbox for fresh (without existing chart) WinForms project? Then...
Here was some discussion about that: https://github.com/dotnet/winforms/discussions/7073#discussioncomment-2618150
But the answers not so obvious :(

Currently in my knowledge: a simple (only server side designer)  user control (chart is simple in this terms for now) will be visible in  controls toolbox in one of this scenarios:
- Nuget package.  _Not our case yet :(_
- Control project added to solution.
- Control in the same project.

In all cases this option must be enabled:
![image](https://user-images.githubusercontent.com/17767561/190419677-b9934f3c-b8be-4133-b98d-8e367e88ec5a.png)


Unfortunately if you simple add reference to a user control dll - this control will not appear at the toolbox 😢 We will be able to use designer with already existing charts on the forms, but we won't be able to add new ones. _I think this is good issue to rise in WinForms repo..._ 

So, to fix this problem we have plenty of options. Here are tow most simple of them: 
- Add `ChartWin.csproj` to your solution. You may need to restart the solution.
- Add this class to your project:
  ```cs
  public class MyChart : System.Windows.Forms.DataVisualization.Charting.Chart
  {
  }
  ```
  rebuild project. Drug and drop `MyChart` control to your form and save it. Then if you wish you can replace all `YourNamespace.MyChart` in `Form*.Designer.cs` with `System.Windows.Forms.DataVisualization.Charting.Chart`.

**Comment by paul1956** [comment]
Thanks, works perfect.
![image](https://user-images.githubusercontent.com/12789369/190530516-11dea0f9-06f2-474f-b7f1-7f89c61fd764.png)
