### ISSUE TITLE
Compatibility with .net core 7?

### ISSUE THREAD

**Issue by capesean** [kirsan31/winforms-datavisualization#36]
When trying to Nuget this into my project, I get:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package WinForms.DataVisualization 1.8.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package WinForms.DataVisualization 1.8.0 supports:
  - net6.0-windows7.0 (.NETCoreApp,Version=v6.0)
  - net7.0-windows7.0 (.NETCoreApp,Version=v7.0)	
```

Any way I can get around that?

**Comment by kirsan31** [comment]
This control fully supports .Net7, but it is a WinForms control, and WinForms is a Windows-only GUI. Therefore, your project must target `net7.0-windows`.

**Comment by capesean** [comment]
Got it, thanks. I had to set the TargetOS to Windows.
