### ISSUE TITLE
Rounding labels

### ISSUE THREAD

**Issue by paul1956** [kirsan31/winforms-datavisualization#38]
Is there a way to round whole numbers to integers in labels, I would like 5.0 to 20.0 to display a 5-20 without the decimal but not round the 2.8 and 22.2.
![image](https://github.com/kirsan31/winforms-datavisualization/assets/12789369/7771fd03-fc6f-483e-8b45-6fa5434d8919)
 If not, could this be added as a feature request in a general sense to allow a FormatingEvent like in DataGridView CellFormatting.

**Comment by kirsan31** [comment]
Am I wright that we are talking about custom labels here?
If yes, then their values are strings - you set it to anything you want.
If no, then axis have `labels format` (not remember exact name) property.

**Comment by paul1956** [comment]
The label format is the same for every label so {0} or {0.0}. I was looking for something that can take the value into account during formatting. This is another issue here about that as well. I can use custom labels but I think the feature is still needed.

**Comment by kirsan31** [comment]
Oh, I again initially misunderstood what you wanted :(
Сustom labels are exactly for this cases. Also you can try to look at [`AxisLabel` datapoint's property](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datavisualization.charting.datapointcustomproperties.axislabel?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.DataVisualization.Charting.DataPointCustomProperties.AxisLabel)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.8.1). It can display any axis label for specific data point:

![image](https://github.com/kirsan31/winforms-datavisualization/assets/17767561/8a7d2c23-3aa3-4dc2-97fd-caba270bfbcb)

**Comment by paul1956** [comment]
Wow, that was not obvious. It doesn't help for my case because there may be no data point where I need it. But using custom labels for me is a perfect solution,
