### ISSUE TITLE
Since v 1.9.0, some chart series are started from (0,0)

### ISSUE THREAD

**Issue by mschmitz2** [kirsan31/winforms-datavisualization#46]
Thank you for your great work on this project!

I have noticed an issue when updating from v1.8.0 to v1.9.0 in some of my charts, but not in others. I am not entirely sure sure what causes this issue. The only thing that sets these plots apart from others that are fine, is that they mix series of different types (3x Line  series and 2x Point  series) though I'm not sure how that would affect things internally.

With v1.9.0 I get this:

![plot_v1 9](https://github.com/kirsan31/winforms-datavisualization/assets/38347746/9a102a33-0b98-4c72-a9bc-c671eb6072a6)

while for the same chart with v1.8.0 I get this, as expected:

![plot_v1 8](https://github.com/kirsan31/winforms-datavisualization/assets/38347746/0ddf15a0-aefa-438a-a396-629fe0699d5d)

Showing the entire x- and y-axes, one can see that for all line plot series the actual first data point is replaced by the point (0,0):

![plot_v1 9_all values](https://github.com/kirsan31/winforms-datavisualization/assets/38347746/267962fd-2430-48bc-8bff-db27c6343ef8)

**Comment by kirsan31** [comment]
> Thank you for your great work on this project!

Thank you 🙏

> I have noticed an issue when updating from v1.8.0 to v1.9.0

Can it be somehow related to `IsXValueIndexed` [breaking change](https://github.com/kirsan31/winforms-datavisualization/releases/tag/1.9)?
If no, then we need a repro project here...

**Comment by mschmitz2** [comment]
> Can it be somehow related to IsXValueIndexed [breaking change](https://github.com/kirsan31/winforms-datavisualization/releases/tag/1.9)?

I don't think it is as I'm not using indexed series here. 

Does this work for you: [ConsoleAppChartTest2.zip](https://github.com/kirsan31/winforms-datavisualization/files/13122041/ConsoleAppChartTest2.zip) ?

I have tried to reduce the code to a minimum from the original solution. I am now plotting the same simple data twice: once as `Point` and once as `Line`. You can see that the data is plotted correctly when plotting as `Point`, but that the first data point is replaced with (0,0) when plotting as `Line`:

![image](https://github.com/kirsan31/winforms-datavisualization/assets/38347746/323471ec-68cb-40f2-8b1b-e4198c490962)

I could debug it up to the location where I set the data to `Chart1.Series`:

```csharp
prop_vals[seriesIdx].xAxVals.Zip(prop_vals[seriesIdx].ySeries, (xVal, o) => (xVal, o.yVal, o.ptLabel))
    .ToList()
    .ForEach(o =>
    {
        var pt = new DataPoint(o.xVal, o.yVal);
        if (o.ptLabel != null)
            pt.Label = o.ptLabel;
        if (double.IsNaN(o.yVal))
            pt.IsEmpty = true;
        Chart1.Series[seriesIdx].Points.Add(pt);
    });
```

after which `Chart1.Series[0].Points` still has the correct values. So something must happen in the background after this.

**Comment by kirsan31** [comment]
Thanks @mschmitz2, I will look into it...

**Comment by kirsan31** [comment]
With points all are ok:
![image](https://github.com/kirsan31/winforms-datavisualization/assets/17767561/8fc7aa38-c8e9-4469-9a00-1ffff4d47f66)
So, this is some kind of drawing glitch🤔 It's all very strange, need more investigation, when I will have a time...
P.s. you have a cross thread problems (accessing controls not from GUI thread) in you app. 
P.p.s try to avoid unnecessary `ToList()` (it's can be a real problem with large data).

**Comment by mschmitz2** [comment]
Thanks for looking into it!

> P.s. you have a cross thread problems (accessing controls not from GUI thread) in you app.

Yes, I removed the code dealing with that for this example since it works fine for the purpose of this.

> P.p.s try to avoid unnecessary ToList() (it's can be a real problem with large data).

Thanks! It's indeed time I go through the code this is extracted from to look for performance improvements. A lot of this has just been adding new features quickly, one of which might have required a List..

**Comment by kirsan31** [comment]
Regression was introduced in 83bdc36379b44eb6bfaa66fbed39b6994327b6c8. 
I implemented the fix. But in my point of view problems was only with 1 points of series:
![image](https://github.com/kirsan31/winforms-datavisualization/assets/17767561/419edd74-5149-428f-8c99-28c093e2a1fa)
Red question is strange (or may be here we have 3 series)?


Also I found that 83bdc36379b44eb6bfaa66fbed39b6994327b6c8 commit introduced a problems with empty points when they are visible:
![image](https://github.com/kirsan31/winforms-datavisualization/assets/17767561/63cce0ea-8050-4d6b-82b2-acc2fee9430d)
I totally missed that empty point can be not so empty 🤦‍♂️🙄

**Comment by mschmitz2** [comment]
Confirming that 1.9.1 fixes all the original issues, including the red case. All back to how it looked with 1.8: 

![image](https://github.com/kirsan31/winforms-datavisualization/assets/38347746/a0769596-8a4a-4fee-a655-f6585b900ca9)

Thanks for the quick fix!
