### ISSUE TITLE
multi-series StackedBar/StackedColum charts not rendering correctly.

### ISSUE THREAD

**Issue by mtagliaf** [kirsan31/winforms-datavisualization#48]
Only one series renders, up against the bottom/left corner of the image. A reproducible example with code can be found in this StackOverflow question:

https://stackoverflow.com/questions/72078617/how-to-use-2-data-series-in-a-bar-graphic-stacked-bars-with-a-chart-component

**Comment by kirsan31** [comment]
I can't understand anything from your explanation, and I also don't see a working (compiled) example from your link.
The only thing I can _indirectly_ suggest is to try setting `IsXValueIndexed = true` for your series that have no _real_ X values.

**Comment by mtagliaf** [comment]
that fixed my issue, thank you.
