### ISSUE TITLE
X Axis with string values

### ISSUE THREAD

**Issue by jorgegregorio** [kirsan31/winforms-datavisualization#50]
since version 1.9.0 (1.8.0 is OK), if i define string values fot the X axis, only de first value is visible, with numeric values I have no problem)

**Comment by kirsan31** [comment]
1.9 [breaking change](https://github.com/kirsan31/winforms-datavisualization/blob/dev/Docs/BreakingChanges.md)?

**Comment by jorgegregorio** [comment]
I think so.

**Comment by kirsan31** [comment]
So, is it working now?

**Comment by jorgegregorio** [comment]
Sorry, works until version 1.8.0. Doesn't wok on 1.9.0 and 1.9.1.

**Comment by kirsan31** [comment]
> Sorry, works until version 1.8.0. Doesn't wok on 1.9.0 and 1.9.1.

Did you tried what described by the link I have provided?

**Comment by jorgegregorio** [comment]
I, setting the IsXValueIndexed fixed the issue. Thanks.
