### ISSUE TITLE
How can I add a Ema Indicator to chart?

### ISSUE THREAD

**Issue by jpr14** [kirsan31/winforms-datavisualization#53]
I want to add a  Ema Indicator to chart of 20 period

**Comment by kirsan31** [comment]
Sorry, I don't know. Do you tried Google it?
https://www.google.com/search?q=c%23+ms+chart+Ema+Indicator&client=ms-android-xiaomi-rev1&sca_esv=597534592&sxsrf=ACQVn0892Q3gCt8J8Fx2Fgd1vvQ89mDm4w%3A1704985611657&ei=CwSgZYfCJ8Hd7_UPz_qp6As&udm=&oq=c%23+ms+chart+Ema+Indicator&gs_lp=EhNtb2JpbGUtZ3dzLXdpei1zZXJwIhljIyBtcyBjaGFydCBFbWEgSW5kaWNhdG9ySN4WUNEPWNEPcAF4AJABAJgBswGgAb0CqgEDMC4yuAEDyAEA-AEBwgIKEAAYRxjWBBiwA-IDBBgAIEGIBgGQBgI&sclient=mobile-gws-wiz-serp
