### ISSUE TITLE
Cannot deserialize Annotation objects

### ISSUE THREAD

**Issue by msroth** [kirsan31/winforms-datavisualization#55]
I have a chart with several annotations (circles, rectangles, lines, and text) that serializes fine and saves as a PNG image fine.  However, when I try to load the saved serialized chart, I get the following error complaining about the Annotation abstract class and a public constructor.  Looking at the source code it seems the Annotation() constructor is protected.  I think the deserializer wants it to be internal or public.  Am I wrong?  Maybe I am deserializing wrong?  Can this constructor be changed?  Thanks for your attention.

Exception message:
Cannot deserialize property. Cannot find default public constructor for type 'System.Windows.Forms.DataVisualization.Charting.Annotation'.

**Comment by kirsan31** [comment]
Can you be more specific? I think we need a code sample here.

**Comment by msroth** [comment]
Is this more helpful?

Snippet of serialize code
=========================
```
if (filename.Length > 0)
{ 
        // save preview image
	// crtCanvas is a System.Windows.Forms.DataVisualizations.Charting.ChartImageFormat
	// added to form in Designer
	
	// this correctly saves an image of the chart
       crtCanvas.SaveImage($"{filename}.png", ChartImageFormat.Png);

	// this correctly saves chart as XML data
    try
    {
        // serialize chart to XML
        ChartSerializer serializer = crtCanvas.Serializer;
        serializer.IsUnknownAttributeIgnored = true;
        serializer.IsResetWhenLoading = false;
        serializer.Save($"{filename}.xml");
        Logger.Info($"Saved chart to {filename}.xml with preview image {filename}.png");
    }
    catch (Exception ex)
    {
        Logger.Error($"Error saving chart to {filename}.xml. {ex.Message}");
    }
}

```
Snippet of deserialize code
===========================
```
if (filename.Length > 0)
{
    try
    {
	 // crtCanvas is a System.Windows.Forms.DataVisualizations.Charting.ChartImageFormat
	 // added to form in Designer 
        ChartSerializer serializer = crtCanvas.Serializer;
		// I've tried reset = false also
        serializer.IsResetWhenLoading = true;
        serializer.IsUnknownAttributeIgnored = true;
        serializer.Load(filename);
        Logger.Info($"Loaded chart file {filename}");
    }
    catch (Exception ex)
    {
        Logger.Error($"Error loading chart file {filename}. {ex.Message}");
    }
}

```
StackTrace
==========

System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot deserialize property. Cannot find default public constructor for type 'System.Windows.Forms.DataVisualization.Charting.Annotation'.
  Source=WinForms.DataVisualization
  StackTrace:
   at System.Windows.Forms.DataVisualization.Charting.Utilities.SerializerBase.GetListNewItem(IList list, String itemTypeName, String& itemName, Boolean& reusedObject)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.DeserializeObject(Object objectToDeserialize, Object parent, String elementName, XmlNode xmlParentNode, XmlDocument xmlDocument)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.DeserializeObject(Object objectToDeserialize, Object parent, String elementName, XmlNode xmlParentNode, XmlDocument xmlDocument)
   at System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.Deserialize(Object objectToDeserialize, Object reader)
   at System.Windows.Forms.DataVisualization.Charting.ChartSerializer.Load(String fileName)
   at xxxxxx.btnLoad_Click(Object sender, EventArgs e) in 
   c:\xxxxxx\frmForm1.cs:line 956

  This exception was originally thrown at this call stack:
    System.Windows.Forms.DataVisualization.Charting.Utilities.SerializerBase.GetListNewItem(System.Collections.IList, string, ref string, ref bool)
    System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.DeserializeObject(object, object, string, System.Xml.XmlNode, System.Xml.XmlDocument)
    System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.DeserializeObject(object, object, string, System.Xml.XmlNode, System.Xml.XmlDocument)
    System.Windows.Forms.DataVisualization.Charting.Utilities.XmlFormatSerializer.Deserialize(object, object)
    System.Windows.Forms.DataVisualization.Charting.ChartSerializer.Load(string)
    xxxxxx.btnLoad_Click(object, System.EventArgs) in frmForm1.cs

2024-02-19 08:49:20.6792|ERROR|frmForm1|Error loading chart file C:\Temp\test.xml. Cannot deserialize property. Cannot find default public constructor for type 'System.Windows.Forms.DataVisualization.Charting.Annotation'.

**Comment by kirsan31** [comment]
Thank you @msroth I will look into it as soon as I can.
One thought came to mind - can you try 1.9.1?

**Comment by msroth** [comment]
Same result using 1.9.1.  I think this is the version I was using previously.  I just upgraded to 1.9.2 this week hoping the problem was corrected.

**Comment by msroth** [comment]
As I continue to hammer at this, I realize I did not mention that the annotations that are being saved are actually subtypes of Annotations.  See image.  So, the hierarchy is Annotation -> RectangleAnnotation -> SketchRectangle (abstract) -> PCompAnnotation.  The PCompAnnotation is what is failing to deserialize.  There could well be an error in my hierarchy that is getting the Serializer all balled up, but as best I can tell, all the intermediate classes have default, internal, parameterless constructors.
![Capture](https://github.com/kirsan31/winforms-datavisualization/assets/4048670/0930bed5-3eb7-4fb0-ad18-56890c7c3922)

**Comment by kirsan31** [comment]
> As I continue to hammer at this, I realize I did not mention that the annotations that are being saved are actually subtypes of Annotations.

This is the main thing I asked when clarifying - whether you use your own classes, or use only native chart functionality.
Because in our applications we use charts with different annotations and everything is fine with serialization/deserialization.

> There could well be an error in my hierarchy that is getting the Serializer all balled up, but as best I can tell, all the intermediate classes have default, internal, parameterless constructors.

I would check the serialization first. Look in the xml file - the class names must be final (e.g. `RectangleAnnotation` but not `Annotation`)...

This is all I can advise without having the source codes.

**Comment by msroth** [comment]
I created clean Annotations and serialized them and deserialized them into my charts.  The issue is clearly my subtypes regardless of where the stack trace points me.  Comparing the XML files the <annotations> element clearly contains my class names and not RectangleAnnotation, etc.  Thanks for your help and sorry for the bother.
