### ISSUE TITLE
Annotation is changing chart's cursor when WaitCursor was used

### ISSUE THREAD

**Issue by idenchev** [kirsan31/winforms-datavisualization#56]
This is a problem which exists since .Net Framework 4.7. Usually I define the charts to have a cross cursor when the mouse is within chart's borders. This is done with:
```
Chart1.Cursor = Cursors.Cross
```
Outside of the chart's border the cursor is the default one - an arrow.

Chart's datasource is a MySQL query. During query execution and chart building I prefer to use the wait cursor, so that the user to be aware that there is an ongoing operation. As long as there is no annotation chosen to be shown everything is fine. Wait cursor is activated before MySQL query starts and the return to the default cursor is done when all charts are built. But if user selects the option to draw an annotation then the defined **cross** cursor for within chart's borders is no longer the case, but inside the chart the cursor is the **wait** one. Outside of the chart everything is fine and the cursor is the default **arrow**. Drawing the annotation happens after the MySQL query is finished and the chart is built.

A workaround is to deactivate the wait cursor just before chart's building. In this case wait cursor covers only the execution time of MySQL query, which could be inconvenient if many charts with a lot of data are to be built, because this takes some time and not having a wait cursor misleads the user that the Windows Form is responsive, but it is not.

Attached at the end you can find a simple VB project showing the issue. Inside the code there are comments explaining it.

Some screenshots depicting the problem are below.

1. Without annotation the cursor inside the chart is the correct one - **cross**:
![noAnno_inside](https://github.com/kirsan31/winforms-datavisualization/assets/37114084/b92a99cb-886f-4cae-8b52-da7a032e2b84)
2. Without annotation the cursor outside of the chart is the correct one - **arrow**:
![noAnno_outside](https://github.com/kirsan31/winforms-datavisualization/assets/37114084/9e2daaa8-f4bf-4ddd-89bb-27c11cc4c6a2)
3. With annotation the cursor inside the chart is the wrong one - **wait**:
![Anno_inside](https://github.com/kirsan31/winforms-datavisualization/assets/37114084/b3425e8f-2300-4bcf-8ba5-80b1499bad27)
4. With annotation the cursor outside of the chart is the the correct one - **arrow**:
![Anno_outside](https://github.com/kirsan31/winforms-datavisualization/assets/37114084/041e5a67-ac37-4815-84da-fa70098f3657)
[Test_Annotation.zip](https://github.com/kirsan31/winforms-datavisualization/files/14502402/Test_Annotation.zip)

**Comment by kirsan31** [comment]
Hi @idenchev 
The problem here is `Control.UseWaitCursor`: 

> true to use the wait cursor for the current control and **all child controls**; otherwise, false.

You can see this yourself if will try your code with:
```vbnet
'.....
Me.UseWaitCursor = False
Chart1.Cursor = Cursors.Cross
Me.UseWaitCursor = True
'.....
```

But You really don't need `Control.UseWaitCursor` at all. Simplify your code to:
```vbnet
Me.Cursor = Cursors.WaitCursor
' all work
Me.Cursor = Cursors.Default
```

**Comment by idenchev** [comment]
I can confirm with joy that your suggestion work like a charm. Thank you so much!
