### ISSUE TITLE
Last Annotation missing when stack bars add up to slightly more than 100%

### ISSUE THREAD

**Issue by HakanL** [kirsan31/winforms-datavisualization#57]
I have a project where we have a chart using StackBar and a fixed-size PlotArea. I noticed that if the bars are over 100 then the last annotate that is bound to a DataPoint disappears. But the bar is displayed fine, it's just the annotation that is gone. Since there are several dependencies to reproduce this I've put it into a repo to show the issue. If you go into the series and just change one of the data points so the total is under 100 then the 3rd annotate shows up, but the example as-is shows the issue. I assume it's an issue in the method `IsAnchorVisible` where it checks if the anchor is inside the plot rectangle, but I'm not sure what the proper fix is.
I've worked around the issue by just re-calculating the last data point if the total is >100, but it's a hack.
Nuget package version: 1.9.2

Repo: https://github.com/HakanL/datavis-issue

**Comment by kirsan31** [comment]
Sorry for long delay @HakanL 🙇‍♂️
I see a problem. It's also somehow related to InnerPlotPosition X location. So if in your example we set `chartArea1.InnerPlotPosition.X` to 33 or less - all will be ok... 🤔

**Comment by kirsan31** [comment]
Ahhhhh I figured it out, all problems are from this line of code:
`chartArea1.AxisY.Maximum = 100D;`
>But the bar is displayed fine, it's just the annotation that is gone.

This is not true, you can see it if set `AxisY.Maximum` to smaller values:
![image](https://github.com/kirsan31/winforms-datavisualization/assets/17767561/e561e228-99a3-4543-9e76-0821ef837060)

You need recalculate `AxisY.Maximum`, or set it to `Auto`, or even use `StackedBar100` chart type.

**Comment by HakanL** [comment]
Thanks for your findings, that makes sense!
