### ISSUE TITLE
candleSticks don't work

### ISSUE THREAD

**Issue by rowi123** [kirsan31/winforms-datavisualization#58]
i use Points.AddXY (if it matters)
i have a working project .net 4.8 and now i use this nuget
i tried adding a series and some bars, but it draws very weird
i have 0 issues with a line graph

expected
![expected](https://github.com/user-attachments/assets/14bd8278-d037-454a-b44b-1cbec7db2fd5)
this nuget
![this nuget](https://github.com/user-attachments/assets/88f0a802-db64-4d39-97d7-0ed2aa7c3d3a)

**Comment by kirsan31** [comment]
I think this may be related to: `IsXValueIndexed` flag: https://github.com/kirsan31/winforms-datavisualization/blob/dev/Docs/BreakingChanges.md

If not, then we need a repro project to check.

**Comment by rowi123** [comment]
wow, now that is a fast reply :)
yes that was it!

to be clear if someone else it reading this, old:

chart.Series.Add( new Series( "candles" )
         {
            ChartArea = "ChartArea",
            Legend = "Legend",
            ChartType = SeriesChartType.Candlestick,
            CustomProperties = "PriceDownColor=#ff0000, PriceUpColor=#4caf50",
            BorderWidth = 0
         } );

new:

chart.Series.Add( new Series( "candles" )
         {
            ChartArea = "ChartArea",
            Legend = "Legend",
            ChartType = SeriesChartType.Candlestick,
            CustomProperties = "PriceDownColor=#ff0000, PriceUpColor=#4caf50",
            BorderWidth = 0,
            IsXValueIndexed = true
         } );

Couldn't you set IsXValueIndexed = true as default?
